import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { useToast } from '@/hooks/use-toast';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ImageIcon, Video, Type, Loader2, X } from 'lucide-react';

interface CreatePostModalProps {
  open: boolean;
  onClose: () => void;
  onSuccess: () => void;
  defaultTab?: 'text' | 'image' | 'video';
}

export const CreatePostModal = ({ open, onClose, onSuccess, defaultTab = 'text' }: CreatePostModalProps) => {
  const { user } = useAuth();
  const { toast } = useToast();
  const [content, setContent] = useState('');
  const [mediaFile, setMediaFile] = useState<File | null>(null);
  const [mediaPreview, setMediaPreview] = useState<string | null>(null);
  const [mediaType, setMediaType] = useState<'image' | 'video' | null>(null);
  const [loading, setLoading] = useState(false);
  const [activeTab, setActiveTab] = useState<'text' | 'image' | 'video'>(defaultTab);

  const handleMediaChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const isImage = file.type.startsWith('image/');
    const isVideo = file.type.startsWith('video/');

    if (!isImage && !isVideo) {
      toast({
        title: 'Invalid file type',
        description: 'Please select an image or video file',
        variant: 'destructive',
      });
      return;
    }

    setMediaFile(file);
    setMediaType(isImage ? 'image' : 'video');
    setMediaPreview(URL.createObjectURL(file));
  };

  const removeMedia = () => {
    setMediaFile(null);
    setMediaPreview(null);
    setMediaType(null);
  };

  const uploadMedia = async (): Promise<string | null> => {
    if (!mediaFile || !user) return null;

    const fileExt = mediaFile.name.split('.').pop();
    const fileName = `${user.id}/${Date.now()}.${fileExt}`;

    const { data, error } = await supabase.storage
      .from('posts')
      .upload(fileName, mediaFile);

    if (error) throw error;

    const { data: { publicUrl } } = supabase.storage
      .from('posts')
      .getPublicUrl(data.path);

    return publicUrl;
  };

  const handleSubmit = async () => {
    if (!user) return;
    if (!content.trim() && !mediaFile) {
      toast({
        title: 'Empty post',
        description: 'Please add some content or media',
        variant: 'destructive',
      });
      return;
    }

    setLoading(true);
    try {
      let mediaUrl = null;
      if (mediaFile) {
        mediaUrl = await uploadMedia();
      }

      const { error } = await supabase.from('posts').insert({
        user_id: user.id,
        content: content.trim() || null,
        media_url: mediaUrl,
        media_type: mediaType || 'text',
        feed_id: '', // Will be auto-generated by trigger
      });

      if (error) throw error;

      toast({
        title: 'Post created!',
        description: 'Your post has been shared',
      });

      setContent('');
      setMediaFile(null);
      setMediaPreview(null);
      setMediaType(null);
      onSuccess();
    } catch (error: any) {
      toast({
        title: 'Error creating post',
        description: error.message,
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="bg-gray-900 border-gray-800 text-white max-w-lg max-h-[85vh] overflow-y-auto my-8">
        <DialogHeader>
          <DialogTitle>Create Post</DialogTitle>
        </DialogHeader>

        <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as any)} className="w-full">
          <TabsList className="grid w-full grid-cols-3 bg-gray-800">
            <TabsTrigger value="text" className="flex items-center space-x-2">
              <Type className="w-4 h-4" />
              <span>Text</span>
            </TabsTrigger>
            <TabsTrigger value="image" className="flex items-center space-x-2">
              <ImageIcon className="w-4 h-4" />
              <span>Image</span>
            </TabsTrigger>
            <TabsTrigger value="video" className="flex items-center space-x-2">
              <Video className="w-4 h-4" />
              <span>Video</span>
            </TabsTrigger>
          </TabsList>

          <div className="mt-4 space-y-4">
            <div>
              <Label htmlFor="content">What's on your mind?</Label>
              <Textarea
                id="content"
                placeholder="Share something..."
                value={content}
                onChange={(e) => setContent(e.target.value)}
                className="mt-2 bg-gray-800 border-gray-700 text-white min-h-[120px]"
                disabled={loading}
              />
            </div>

            <TabsContent value="image" className="mt-0">
              <div>
                <Label htmlFor="image">Upload Image</Label>
                <Input
                  id="image"
                  type="file"
                  accept="image/*"
                  onChange={handleMediaChange}
                  className="mt-2 bg-gray-800 border-gray-700 text-white"
                  disabled={loading}
                />
              </div>
            </TabsContent>

            <TabsContent value="video" className="mt-0">
              <div>
                <Label htmlFor="video">Upload Video</Label>
                <Input
                  id="video"
                  type="file"
                  accept="video/*"
                  onChange={handleMediaChange}
                  className="mt-2 bg-gray-800 border-gray-700 text-white"
                  disabled={loading}
                />
              </div>
            </TabsContent>

            {mediaPreview && (
              <div className="relative rounded-lg overflow-hidden">
                {mediaType === 'image' && (
                  <img src={mediaPreview} alt="Preview" className="w-full" />
                )}
                {mediaType === 'video' && (
                  <video src={mediaPreview} controls className="w-full" />
                )}
                <Button
                  onClick={removeMedia}
                  size="icon"
                  variant="destructive"
                  className="absolute top-2 right-2"
                  disabled={loading}
                >
                  <X className="w-4 h-4" />
                </Button>
              </div>
            )}

            <div className="flex justify-end space-x-2">
              <Button
                onClick={onClose}
                variant="outline"
                className="border-gray-700 text-white hover:bg-gray-800"
                disabled={loading}
              >
                Cancel
              </Button>
              <Button
                onClick={handleSubmit}
                disabled={loading || (!content.trim() && !mediaFile)}
                className="bg-gradient-to-r from-pink-500 to-blue-500"
              >
                {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                Post
              </Button>
            </div>
          </div>
        </Tabs>
      </DialogContent>
    </Dialog>
  );
};