import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from './useAuth';
import usernameCache from '@/lib/username-cache';

interface ProfileCompletionStatus {
  isComplete: boolean;
  needsUsername: boolean;
  needsDisplayName: boolean;
  currentUsername: string | null;
  currentDisplayName: string | null;
  isLoading: boolean;
  isAutoGeneratedUsername: boolean;
}

// Regex pattern to detect auto-generated usernames (e.g., "user_abc12345" or "email_abc12345_1")
const AUTO_GENERATED_USERNAME_PATTERN = /^[a-z0-9_]+_[a-f0-9]{8}(_\d+)?$/i;

export const isAutoGeneratedUsername = (username: string | null): boolean => {
  if (!username) return false;
  return AUTO_GENERATED_USERNAME_PATTERN.test(username);
};

export const useProfileCompletion = () => {
  const { user } = useAuth();
  const [status, setStatus] = useState<ProfileCompletionStatus>({
    isComplete: true, // Assume complete until proven otherwise
    needsUsername: false,
    needsDisplayName: false,
    currentUsername: null,
    currentDisplayName: null,
    isLoading: true,
    isAutoGeneratedUsername: false,
  });

  const checkProfileCompletion = useCallback(async () => {
    if (!user) {
      setStatus(prev => ({ ...prev, isLoading: false, isComplete: true }));
      return;
    }

    try {
      const { data: profile, error } = await supabase
        .from('profiles')
        .select('username, display_name, profile_completed')
        .eq('id', user.id)
        .maybeSingle();

      if (error && error.code !== 'PGRST116') {
        console.error('Error checking profile completion:', error);
        setStatus(prev => ({ ...prev, isLoading: false, isComplete: true }));
        return;
      }

      if (!profile) {
        // No profile exists - needs completion
        setStatus({
          isComplete: false,
          needsUsername: true,
          needsDisplayName: true,
          currentUsername: null,
          currentDisplayName: null,
          isLoading: false,
          isAutoGeneratedUsername: false,
        });
        return;
      }

      // CRITICAL: Check for auto-generated username FIRST, regardless of profile_completed flag
      // This ensures users with bad data still get prompted to complete their profile
      const hasAutoGeneratedUsername = isAutoGeneratedUsername(profile.username);
      const needsDisplayName = !profile.display_name || profile.display_name.trim() === '';
      const needsUsername = !profile.username || hasAutoGeneratedUsername;

      // If username is auto-generated, ALWAYS require completion regardless of flag
      if (hasAutoGeneratedUsername || needsDisplayName) {
        // Update the profile_completed flag in DB if it's incorrectly set to true
        if (profile.profile_completed && (hasAutoGeneratedUsername || needsDisplayName)) {
          await supabase
            .from('profiles')
            .update({ profile_completed: false })
            .eq('id', user.id);
        }

        setStatus({
          isComplete: false,
          needsUsername,
          needsDisplayName,
          currentUsername: profile.username,
          currentDisplayName: profile.display_name,
          isLoading: false,
          isAutoGeneratedUsername: hasAutoGeneratedUsername,
        });
        return;
      }

      // Profile is truly complete - has proper username and display name
      if (profile.profile_completed) {
        // Cache the username -> userId mapping for fast lookups
        if (profile.username) {
          usernameCache.set(profile.username, user.id);
        }

        setStatus({
          isComplete: true,
          needsUsername: false,
          needsDisplayName: false,
          currentUsername: profile.username,
          currentDisplayName: profile.display_name,
          isLoading: false,
          isAutoGeneratedUsername: false,
        });
        return;
      }

      // Profile not marked complete but has proper data - mark it complete
      if (!needsUsername && !needsDisplayName) {
        await supabase
          .from('profiles')
          .update({ profile_completed: true })
          .eq('id', user.id);

        if (profile.username) {
          usernameCache.set(profile.username, user.id);
        }

        setStatus({
          isComplete: true,
          needsUsername: false,
          needsDisplayName: false,
          currentUsername: profile.username,
          currentDisplayName: profile.display_name,
          isLoading: false,
          isAutoGeneratedUsername: false,
        });
        return;
      }

      setStatus({
        isComplete: false,
        needsUsername,
        needsDisplayName,
        currentUsername: profile.username,
        currentDisplayName: profile.display_name,
        isLoading: false,
        isAutoGeneratedUsername: hasAutoGeneratedUsername,
      });
    } catch (error) {
      console.error('Error in checkProfileCompletion:', error);
      setStatus(prev => ({ ...prev, isLoading: false, isComplete: true }));
    }
  }, [user]);

  useEffect(() => {
    checkProfileCompletion();
  }, [checkProfileCompletion]);

  const markProfileComplete = useCallback(async () => {
    if (!user) return false;

    try {
      const { error } = await supabase
        .from('profiles')
        .update({ profile_completed: true, updated_at: new Date().toISOString() })
        .eq('id', user.id);

      if (error) throw error;

      setStatus(prev => ({ ...prev, isComplete: true }));
      return true;
    } catch (error) {
      console.error('Error marking profile complete:', error);
      return false;
    }
  }, [user]);

  const refreshStatus = useCallback(() => {
    setStatus(prev => ({ ...prev, isLoading: true }));
    checkProfileCompletion();
  }, [checkProfileCompletion]);

  return {
    ...status,
    markProfileComplete,
    refreshStatus,
  };
};