import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from './useAuth';

interface ProfileCompletionStatus {
  isComplete: boolean;
  needsUsername: boolean;
  needsDisplayName: boolean;
  currentUsername: string | null;
  currentDisplayName: string | null;
  isLoading: boolean;
}

export const useProfileCompletion = () => {
  const { user } = useAuth();
  const [status, setStatus] = useState<ProfileCompletionStatus>({
    isComplete: true, // Assume complete until proven otherwise
    needsUsername: false,
    needsDisplayName: false,
    currentUsername: null,
    currentDisplayName: null,
    isLoading: true,
  });

  const checkProfileCompletion = useCallback(async () => {
    if (!user) {
      setStatus(prev => ({ ...prev, isLoading: false, isComplete: true }));
      return;
    }

    try {
      const { data: profile, error } = await supabase
        .from('profiles')
        .select('username, display_name, profile_completed')
        .eq('id', user.id)
        .maybeSingle();

      if (error && error.code !== 'PGRST116') {
        console.error('Error checking profile completion:', error);
        setStatus(prev => ({ ...prev, isLoading: false, isComplete: true }));
        return;
      }

      if (!profile) {
        // No profile exists - needs completion
        setStatus({
          isComplete: false,
          needsUsername: true,
          needsDisplayName: true,
          currentUsername: null,
          currentDisplayName: null,
          isLoading: false,
        });
        return;
      }

      // Check if profile is already marked as completed
      if (profile.profile_completed) {
        setStatus({
          isComplete: true,
          needsUsername: false,
          needsDisplayName: false,
          currentUsername: profile.username,
          currentDisplayName: profile.display_name,
          isLoading: false,
        });
        return;
      }

      // Check for auto-generated username pattern (e.g., "user_abc12345" or "email_abc12345")
      const hasAutoGeneratedUsername = profile.username && 
        /^[a-z0-9_]+_[a-f0-9]{8}(_\d+)?$/i.test(profile.username);

      const needsUsername = !profile.username || hasAutoGeneratedUsername;
      const needsDisplayName = !profile.display_name;

      setStatus({
        isComplete: !needsUsername && !needsDisplayName,
        needsUsername,
        needsDisplayName,
        currentUsername: profile.username,
        currentDisplayName: profile.display_name,
        isLoading: false,
      });
    } catch (error) {
      console.error('Error in checkProfileCompletion:', error);
      setStatus(prev => ({ ...prev, isLoading: false, isComplete: true }));
    }
  }, [user]);

  useEffect(() => {
    checkProfileCompletion();
  }, [checkProfileCompletion]);

  const markProfileComplete = useCallback(async () => {
    if (!user) return false;

    try {
      const { error } = await supabase
        .from('profiles')
        .update({ profile_completed: true, updated_at: new Date().toISOString() })
        .eq('id', user.id);

      if (error) throw error;

      setStatus(prev => ({ ...prev, isComplete: true }));
      return true;
    } catch (error) {
      console.error('Error marking profile complete:', error);
      return false;
    }
  }, [user]);

  const refreshStatus = useCallback(() => {
    setStatus(prev => ({ ...prev, isLoading: true }));
    checkProfileCompletion();
  }, [checkProfileCompletion]);

  return {
    ...status,
    markProfileComplete,
    refreshStatus,
  };
};